name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
  - andriydruk
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of RxDNNSD are you running?
      placeholder: X.X.XX
      value: "0.9.16"
    validations:
      required: true
  - type: dropdown
    id: api
    attributes:
      label: What API do you use?
      multiple: false
      options:
        - Bindable (recommended)
        - Embedded
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: What device / emulator do you use?
      description: Please paste device model
    validations:
      required: true
  - type: input
    id: androidapi
    attributes:
      label: What Android API version is on your device?
      description: Please paste Android API version
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Could you reproduce this issue in samples?
      description: 
      options:
        - label: Yes, I can reproduce this issue in sample app of this repo?
          required: false
        - label: Yes, I can reproduce this issue in [Bonjour Browser](https://github.com/andriydruk/BonjourBrowser)?
          required: false